name: Build TA-Lib Wheels

on:
  workflow_dispatch:

jobs:
  build-wheels:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Download TA-Lib C library
        run: |
          Invoke-WebRequest `
            -Uri 'https://sourceforge.net/projects/ta-lib/files/ta-lib/0.4.0/ta-lib-0.4.0-msvc.zip/download' `
            -OutFile 'ta-lib.zip'
          Expand-Archive ta-lib.zip -DestinationPath 'C:\ta-lib'

      - name: Set TA-Lib env variables
        run: |
          echo "TA_LIBRARY_PATH=C:\ta-lib\lib"  | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "TA_INCLUDE_PATH=C:\ta-lib\include"  | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel setuptools

      - name: Build wheel
        run: |
          pip wheel ta-lib --no-deps -w dist

      - name: Upload artefact
        uses: actions/upload-artifact@v3
        with:
          name: wheels-${{ matrix.python-version }}
          path: dist\*.whl
